# Dependencies
markdown:        redcarpet
highlighter:     pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gary Roumanis
tagline:          'Personal Webpage'
baseurl:          '/'
paginate:         5

author:
  name:           'Gary Roumanis'
  url:            garyroumanis.com